import type { Metadata } from "next";
import LegalPage from "../components/LegalPage";

export const metadata: Metadata = { title: "Terms of service — Esim.free", description: "Terms governing purchases of travel eSIM plans from Esim.free.", alternates: { canonical: "/terms/" } };

export default function TermsPage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms of service" lead="These terms govern the purchase and use of prepaid travel eSIM products sold by Esim.free.">
      <section><h2>1. Seller and scope</h2><p>Esim.free is the company that offers, sells and supports the digital eSIM products shown on this website. These Terms apply to every order placed through Esim.free. The customer’s checkout, transaction receipt or invoice identifies the legal payment merchant and any additional transaction-specific terms.</p></section>
      <section><h2>2. The product</h2><p>An eSIM is a digital mobile-data profile installed on a compatible device. We sell fixed, premade catalogue products; we do not sell consultations, custom development or personalised services. Unless the product page states otherwise, our plans are data-only and do not include a telephone number, voice calls or SMS. Plan destination, data allowance, validity and price are shown before purchase.</p></section>
      <section><h2>3. Orders and payment</h2><p>You must provide a valid email address and accurate order information. Prices are displayed in USD unless stated otherwise. Applicable tax is calculated or shown at checkout. The payment processor or Merchant of Record displayed at checkout processes the payment and may also handle tax, invoicing and transaction-related requests under its own checkout terms.</p></section>
      <section><h2>4. Digital delivery</h2><p>After successful payment, we electronically deliver the eSIM QR code or activation details and installation guide. Delivery is normally completed within minutes but may be delayed by payment review, incorrect contact details or supplier/network availability. Contact us if delivery does not arrive.</p></section>
      <section><h2>5. Compatibility and activation</h2><p>You are responsible for confirming that your device supports eSIM, is carrier-unlocked and supports the destination networks. Install the eSIM while connected to reliable Wi‑Fi and follow the supplied instructions. A QR code may be installable only once. Do not delete an installed profile until the plan has ended unless support instructs you to do so.</p></section>
      <section><h2>6. Coverage and fair use</h2><p>Coverage, speed, 5G availability and network selection depend on local operators, geography, congestion, device capability and fair-use rules. “Unlimited” plans may include a daily high-speed allowance followed by reduced speeds, as disclosed in the plan details. We do not guarantee uninterrupted service in every location.</p></section>
      <section><h2>7. Acceptable use</h2><p>You may use the eSIM only for lawful personal or business connectivity. You must not use it for fraud, abuse, network interference, unlawful content, resale without permission or any activity prohibited by local law or the underlying network rules.</p></section>
      <section><h2>8. Refunds</h2><p>Refund eligibility is governed by our <a href="/refunds/">Refund Policy</a>. Nothing in these Terms limits non-waivable consumer rights that apply to you.</p></section>
      <section><h2>9. Liability</h2><p>To the maximum extent permitted by law, Esim.free is not responsible for indirect or consequential loss, loss caused by an incompatible or locked device, incorrect installation, local network outages or use outside the purchased coverage. Our aggregate liability for a claim will not exceed the amount paid for the affected plan, except where law requires otherwise.</p></section>
      <section><h2>10. Upstream connectivity</h2><p>We source mobile connectivity and eSIM provisioning from third-party network and technology suppliers. Esim.free remains the customer-facing seller and support contact for products purchased from this website. Local mobile operators and provisioning suppliers may apply technical network rules needed to provide the purchased plan.</p></section>
      <section><h2>11. Changes and contact</h2><p>We may update these Terms for future orders. The version in force when you order applies to that transaction. Questions may be sent to <a href="mailto:staskochukov@gmail.com">staskochukov@gmail.com</a>.</p></section>
    </LegalPage>
  );
}
